Line following in Final World
ppswaroopa/Aue8230Spring2022_Group7 pull request #12
Opened 2022-04-19 06:27 UTC by zainul-b

2022-04-19 15:54 UTC, ppswaroopa requested changes
Add the video for demo as well. I'll approve it together

2022-04-19 17:03 UTC, zainul-b commented
Added the video!

2022-04-19 19:47 UTC, zainul-b commented
April tag testing done, added video of the same

2022-04-20 00:02 UTC, ppswaroopa commented
Good to go.

2022-04-20 00:03 UTC, merged